// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriTEC.Data;

#nullable disable

namespace NutriTEC.Migrations
{
    [DbContext(typeof(NutriTECDb))]
    [Migration("20230606034137_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriTEC.Models.Administrador", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Cedula");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("NutriTEC.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CaloriasMaximas")
                        .HasColumnType("integer");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IMC")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisResidencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("NutriTEC.Models.Consumo", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_cliente"));

                    b.Property<int>("Almuerzo")
                        .HasColumnType("integer");

                    b.Property<int>("Cena")
                        .HasColumnType("integer");

                    b.Property<int>("Desayuno")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Merienda_Mañana")
                        .HasColumnType("integer");

                    b.Property<int>("Merienda_Tarde")
                        .HasColumnType("integer");

                    b.HasKey("Id_cliente");

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("NutriTEC.Models.GestionPlanes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Almuerzo")
                        .HasColumnType("integer");

                    b.Property<int>("CaloríasTotales")
                        .HasColumnType("integer");

                    b.Property<int>("CedulaNutricionista")
                        .HasColumnType("integer");

                    b.Property<int>("Cena")
                        .HasColumnType("integer");

                    b.Property<int>("Desayuno")
                        .HasColumnType("integer");

                    b.Property<int>("Merienda_Mañana")
                        .HasColumnType("integer");

                    b.Property<int>("Merienda_Tarde")
                        .HasColumnType("integer");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GestiondePlanes");
                });

            modelBuilder.Entity("NutriTEC.Models.GestionProductos", b =>
                {
                    b.Property<int>("Codigo_barras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo_barras"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Calcio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Carbohidratos")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Energia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Grasa")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hierro")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Porcion")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Proteina")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Sodio")
                        .HasColumnType("numeric");

                    b.Property<string>("Vitaminas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo_barras");

                    b.ToTable("GestiondeProductos");
                });

            modelBuilder.Entity("NutriTEC.Models.Medidas", b =>
                {
                    b.Property<int>("Id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_cliente"));

                    b.Property<decimal>("Caderas")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cintura")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cuello")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Porcentaje_grasa")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Porcentaje_musculo")
                        .HasColumnType("numeric");

                    b.HasKey("Id_cliente");

                    b.ToTable("Medida");
                });

            modelBuilder.Entity("NutriTEC.Models.Nutricionista", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cedula"));

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Codigo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Cumpleaños")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IMC")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tarjeta")
                        .HasColumnType("integer");

                    b.Property<int>("TipoCobro")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Cedula");

                    b.ToTable("Nutricionistas");
                });

            modelBuilder.Entity("NutriTEC.Models.PacientesAsociados", b =>
                {
                    b.Property<int>("CedulaNutricionista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CedulaNutricionista"));

                    b.Property<int>("CedulaPaciente")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPlan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanAsignado")
                        .HasColumnType("integer");

                    b.HasKey("CedulaNutricionista");

                    b.ToTable("PacienteAsociado");
                });

            modelBuilder.Entity("NutriTEC.Models.TipoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposdePago");
                });
#pragma warning restore 612, 618
        }
    }
}
