// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriTEC.Data;

#nullable disable

namespace NutriTEC.Migrations.GestionProductosDbMigrations
{
    [DbContext(typeof(GestionProductosDb))]
    [Migration("20230604073407_thirdmigration")]
    partial class thirdmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriTEC.Models.GestionProductos", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("Calcio")
                        .HasColumnType("integer");

                    b.Property<int>("Carbohidratos")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Energia")
                        .HasColumnType("integer");

                    b.Property<int>("Grasa")
                        .HasColumnType("integer");

                    b.Property<int>("Hierro")
                        .HasColumnType("integer");

                    b.Property<int>("Porcion")
                        .HasColumnType("integer");

                    b.Property<int>("Proteina")
                        .HasColumnType("integer");

                    b.Property<int>("Sodio")
                        .HasColumnType("integer");

                    b.Property<string>("Vitaminas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("GestiondeProductos");
                });
#pragma warning restore 612, 618
        }
    }
}
