// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriTEC.Data;

#nullable disable

namespace NutriTEC.Migrations.GestionPlanesDbMigrations
{
    [DbContext(typeof(GestionPlanesDb))]
    partial class GestionPlanesDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriTEC.Models.GestionPlanes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Almuerzo")
                        .HasColumnType("integer");

                    b.Property<int>("CaloríasTotales")
                        .HasColumnType("integer");

                    b.Property<int>("CedulaNutricionista")
                        .HasColumnType("integer");

                    b.Property<int>("Cena")
                        .HasColumnType("integer");

                    b.Property<int>("Desayuno")
                        .HasColumnType("integer");

                    b.Property<int>("MeriendaMañana")
                        .HasColumnType("integer");

                    b.Property<int>("MeriendaTarde")
                        .HasColumnType("integer");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GestiondePlanes");
                });
#pragma warning restore 612, 618
        }
    }
}
